### ISSUE TITLE
quick question of table data extraction

### ISSUE THREAD

**Issue by mravunni** [Layout-Parser/layout-parser#10]
Is this only for identifying the layout or is there an extraction framework to extract the identified tables?

**Comment by lolipopshock** [comment]
The short answer is yes! 

1. Currently, you could use the model trained on `PubLayNet` to detect the table regions, refer to  https://layout-parser.readthedocs.io/en/latest/notes/modelzoo.html
```
import layoutparser as lp
model = lp.Detectron2LayoutModel(
            config_path ='lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config', # In model catalog
            label_map   ={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"}, # In model`label_map`
            extra_config=["MODEL.ROI_HEADS.SCORE_THRESH_TEST", 0.8] # Optional
        )
layout = model.detect(image)
table_regions = [ele for ele in layout if ele.type == 'Table']
```
2. We are working on some dedicated table detection models and will update our repositories very soon. Please stay tuned.

**Comment by Yashsethi24** [comment]
Hey ! Can we train this model ourselves? In such a way that it will have existing features and additional to detect the table format. If yes, please do let me know how? 

Thank you :)

**Comment by lolipopshock** [comment]
> Hey ! Can we train this model ourselves? In such a way that it will have existing features and additional to detect the table format. If yes, please do let me know how?
> 
> Thank you :)

The short answer is yes - you could find more details in this repository: https://github.com/Layout-Parser/layout-model-training. And we will provide more details soon.

**Comment by lolipopshock** [comment]
Also see #19 - the table region detection model trained on the docbank dataset has been added.
