### ISSUE TITLE
'GCVAgent' object has no attribute '_client'

### ISSUE THREAD

**Issue by junxi-liu** [Layout-Parser/layout-parser#111]
Hi, when I was running the tutorial of "OCR tables and parse the output", when I was trying to obtain the result:

`res = ocr_agent.detect(image, return_response=True)`

The response was 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/layoutparser/ocr/gcv_agent.py", line 168, in detect
    res = self._detect(img_content)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/layoutparser/ocr/gcv_agent.py", line 134, in _detect
    response = self._client.document_text_detection(
AttributeError: 'GCVAgent' object has no attribute '_client'`

I googled and some sites said The Client() class was removed in the Client Library v0.25.1 and replaced with ImageAnnotatorClient().

Was this a problem? Thank you.

**Comment by its-kind-of** [comment]
Could you please share your solution with me? I'm experiencing the same problem.
**AttributeError: 'GCVAgent' object has no attribute '_client'**

**Comment by its-kind-of** [comment]
Could you please share your solution with me? I'm experiencing the same problem.
_AttributeError: 'GCVAgent' object has no attribute '_client'_

**Comment by its-kind-of** [comment]
Could you please share your solution with me? I'm experiencing the same problem.
_AttributeError: 'GCVAgent' object has no attribute 'client'_

**Comment by dokd233622** [comment]
Same here..

**Comment by bsuresh14061992** [comment]
send me the code please

**Comment by dadasmash** [comment]
same here

**Comment by Keitaro-Ninomiya** [comment]
same here

**Comment by JOKERKING88** [comment]
AttributeError: 'GCVAgent' object has no attribute '_client'

**Comment by JOKERKING88** [comment]
This is not a bug: it just says that your google credentials are wrong. As seen in the documentation: 
https://layout-parser.readthedocs.io/en/stable/example/parse_ocr/index.html
ocr_agent = lp.GCVAgent.with_credential("<path/to/your/credential>",
                                       languages = ['en'])
The <path/to/your/credential> part is what causing this error: you should go to Google Cloud Vision and create a new credential and download it as json file like this one: /Users/Downloads/XXXXX-YYYY-99889988-zz987656abc88.json
Then the OCR agent should be:
ocr_agent = lp.GCVAgent.with_credential("/Users/Downloads/XXXXX-YYYY-99889988-zz987656abc88.json",
                                       languages = ['en'])
please read:
https://cloud.google.com/functions/docs/tutorials/ocr
