### ISSUE TITLE
instantiating lp.GCVAgent.with_credential returns module 'google.cloud.vision' has no attribute 'types' 

### ISSUE THREAD

**Issue by apoorvalal** [Layout-Parser/layout-parser#12]
Thanks for putting this amazing looking library together. I tried to work through the Table example in the documentation and get 
a `no attribute 'types'` error when I run this line

```
ocr_agent = lp.GCVAgent.with_credential("/home/alal/keys/sandbox-7f8884d01b79.json", 
                                        languages = ['en'])
>module 'google.cloud.vision' has no attribute 'types'
```
I am running `lp` in a conda environment on ubuntu 18.04., have installed `google.cloud.vision`, and have enabled it on console.cloud.google.com and have `GOOGLE_APPLICATION_CREDENTIALS` in my path.

I've also verified that I can run the document-text tutorial in my conda environment https://cloud.google.com/vision/docs/fulltext-annotations.

**Comment by lolipopshock** [comment]
Ahh that should be a problem related to the `google.cloud.vision` APIs. Could you share the exact version of the API via `pip show google-cloud-vision`?

**Comment by apoorvalal** [comment]
Thanks for the prompt response. I have `google-cloud-vision` 2.3.0.

**Comment by apoorvalal** [comment]
Ah, I just looked into dependencies and realised that I need GCV 1.0. Rolled back the version and it worked fine. 
I got the dependencies wrong. I'm not sure why 

```
# Install the ocr components when necessary
pip install layoutparser[ocr]
```
this line didn't run for me.
