### ISSUE TITLE
Detectron2 Package not Working

### ISSUE THREAD

**Issue by JacobsDylan** [Layout-Parser/layout-parser#120]
"module layoutparser has no attribute Detectron2LayoutModel"

My computer (Mac OS) throws an error whenever I try to use the Detectron2 package in a program. I've downloaded this package a number of different ways and have been unable to solve the problem. I installed PyTorch using pip.

**Comment by lolipopshock** [comment]
I think this issue correspond to your latest issue #121  -- I've answered there and I'll close this one first. :)
