### ISSUE TITLE
AttributeError: module layoutparser has no attribute Detectron2LayoutModel

### ISSUE THREAD

**Issue by anglilian** [Layout-Parser/layout-parser#122]
I ran the following lines:
`pip install layoutparser`
`import layoutparser as lp`
`model = lp.Detectron2LayoutModel('lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config',
                                 extra_config=["MODEL.ROI_HEADS.SCORE_THRESH_TEST", 0.8],
                                 label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"})`

Getting the following error even though I have downloaded Dectectron2 following this [walkthrough](https://ivanpp.cc/detectron2-walkthrough-windows/#step3installdetectron2). I also successfully downloaded torchflow.
`AttributeError: module layoutparser has no attribute Detectron2LayoutModel`

This is what I see when I check my installation. I use windows. The layoutparser version is layoutparser-0.3.2
![image](https://user-images.githubusercontent.com/43257301/158903556-e9d8482e-800b-4732-a3f0-89eeebae4e4a.png)

I was looking for my CUDA version by running `nvcc --version` but I get this from my terminal
`'nvcc' is not recognized as an internal or external command,
operable program or batch file.`

Thank you in advance for helping look into this issue!

**Comment by anikde** [comment]
What was the solution to this issue?

**Comment by aFcFzF** [comment]
dir the modules ,find use  `lp.models.Detectron2LayoutModel`
