### ISSUE TITLE
segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by ElToro13** [Layout-Parser/layout-parser#125]
I am using AWS EC2 Ubuntu 18.04. I was able to install everything successfully. While I was trying to load Detectron2LayoutModel, I get following error
```
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

**To Reproduce**
I launched a t2.large AWS Ubuntu 18.04 and ran following command

1. sudo apt-get update
2. sudo apt install python3-pip -y
3. python3 -m pip install --upgrade pip
4. pip3 install scikit-build
5. pip3 install layoutparser torchvision && pip3 install "detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.5#egg=detectron2"

and then ran the following script.

```python
import layoutparser as lp
model = lp.Detectron2LayoutModel('lp://PubLayNet/mask_rcnn_X_101_32x8d_FPN_3x/config',extra_config=["MODEL.ROI_HEADS.SCORE_THRESH_TEST", 0.65],
                                 label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"})
```
Output - 

```
python3: Relink `/lib/x86_64-linux-gnu/libsystemd.so.0' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)
```

**Environment**
1. Ubuntu 18.04 - AWS t2.large Instance
7. layout parser version = 0.3.2
2. Python 3.6.9

Any one else facing this issue?

**Comment by FalconGold** [comment]
This should help

```
pip3 install opencv-python-headless==4.5.4.60
```

**Comment by ElToro13** [comment]
> This should help
> 
> ```
> pip3 install opencv-python-headless==4.5.4.60
> ```

Thanks. It worked!
