### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by sriprad** [Layout-Parser/layout-parser#13]
Hi Team,
Thank you for all the great work. It looks amazing. 
I tried installing pip install layoutparser but it thrown me the below error,
can you please let me know how to rectify this,

ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-s13j7o41\\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-s13j7o41\\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-wheel-awmfv0cr'
       cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-s13j7o41\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\
  Complete output (22 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.8\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.8\pycocotools
  running build_ext
  cythoning pycocotools/_mask.pyx to pycocotools\_mask.c
  C:\Users\pss.ch\AppData\Roaming\Python\Python38\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-s13j7o41\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\pycocotools\_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\common
  creating build\temp.win-amd64-3.8\Release\pycocotools
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\pss.ch\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -I./common "-IC:\Program Files\Anaconda\include" "-IC:\Program Files\Anaconda\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\./common/maskApi.obj -Wno-cpp -Wno-unused-function -std=c99
  cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-s13j7o41\\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-s13j7o41\\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-w4euj5sb\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\pss.ch\AppData\Roaming\Python\Python38\Include\pycocotools'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-s13j7o41\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\pycocotools
    copying pycocotools\coco.py -> build\lib.win-amd64-3.8\pycocotools
    copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.8\pycocotools
    copying pycocotools\mask.py -> build\lib.win-amd64-3.8\pycocotools
    copying pycocotools\__init__.py -> build\lib.win-amd64-3.8\pycocotools
    running build_ext
    skipping 'pycocotools\_mask.c' Cython extension (up-to-date)
    building 'pycocotools._mask' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\common
    creating build\temp.win-amd64-3.8\Release\pycocotools
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\AppData\Roaming\Python\Python38\site-packages\numpy\core\include -I./common "-IC:\Program Files\Anaconda\include" "-IC:\Program Files\Anaconda\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\./common/maskApi.obj -Wno-cpp -Wno-unused-function -std=c99
    cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-s13j7o41\\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-s13j7o41\\pycocotools_6c1fc2cce84542a8be1c0cbeacfda632\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-w4euj5sb\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\AppData\Roaming\Python\Python38\Include\pycocotools' Check the logs for full command output.

**Comment by lolipopshock** [comment]
Could you check #11 ?

**Comment by engineerchange** [comment]
I had a similar issue today.

I think this [commit](https://github.com/Layout-Parser/layout-parser/commit/e9cd85d40829de79102ced04a41ea46483d95e93) doesn't solve the problem of #11 for Windows users - this change is up-to-date in pypi now, and I got the same error as above with a fresh `pip install layoutparser` today. When I tried pip installing the latest version of pycocotools (2.0.2) on my Windows 10 machine, I still got a similar error as above.

I think the resolution is changing pycocotools's compiler flag for Windows users. I was able to follow [these instructions](https://github.com/cocodataset/cocoapi/issues/169#issuecomment-654257384) that git clone the coco library and make a smaller change to a compiler flag in the setup.py to install pycocotools. Then, I had to `git clone https://github.com/Layout-Parser/layout-parser.git`, comment out the pycocotools install in setup.py, and run `python setup.py install` and it ran through the rest of the install fine for me.

**Comment by lolipopshock** [comment]
Thanks @engineerchange! And you might want to try `pip install -U "git+https://github.com/layout-parser/layout-parser.git#egg=layoutparser"` (with `-U` and downloading source from github rather than pypi). But anyhow we are going to update the pypi version as well so it shouldn't be an issue in the future.

**Comment by psanca27** [comment]
> 
> 
> I had a similar issue today.
> 
> I think this [commit](https://github.com/Layout-Parser/layout-parser/commit/e9cd85d40829de79102ced04a41ea46483d95e93) doesn't solve the problem of #11 for Windows users - this change is up-to-date in pypi now, and I got the same error as above with a fresh `pip install layoutparser` today. When I tried pip installing the latest version of pycocotools (2.0.2) on my Windows 10 machine, I still got a similar error as above.
> 
> I think the resolution is changing pycocotools's compiler flag for Windows users. I was able to follow [these instructions](https://github.com/cocodataset/cocoapi/issues/169#issuecomment-654257384) that git clone the coco library and make a smaller change to a compiler flag in the setup.py to install pycocotools. Then, I had to `git clone https://github.com/Layout-Parser/layout-parser.git`, comment out the pycocotools install in setup.py, and run `python setup.py install` and it ran through the rest of the install fine for me.

Had the same issue on Windows 10 and this solved the problem! Thanks a lot



> 
> 
> Thanks @engineerchange! And you might want to try `pip install -U "git+https://github.com/layout-parser/layout-parser.git#egg=layoutparser"` (with `-U` and downloading source from github rather than pypi). But anyhow we are going to update the pypi version as well so it shouldn't be an issue in the future.

This suggested solution did not work from me

**Comment by ankit-crossml** [comment]
Hi All,

I am also facing the below error:

`AssertionError: Requires fvcore>=0.1.2
`

And when I try to install this then I get following dependency errors:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
layoutparser 0.1.3 requires fvcore==0.1.1.post20200623, but you have fvcore 0.1.5.post20210410 which is incompatible.
layoutparser 0.1.3 requires pycocotools==2.0.1, but you have pycocotools 2.0.2 which is incompatible.
```

Could anyone please help me with the working installation version?

Regards,
Ankit Aggarwal

**Comment by lolipopshock** [comment]
> Hi All,
> 
> I am also facing the below error:
> 
> `AssertionError: Requires fvcore>=0.1.2 `
> 
> And when I try to install this then I get following dependency errors:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> layoutparser 0.1.3 requires fvcore==0.1.1.post20200623, but you have fvcore 0.1.5.post20210410 which is incompatible.
> layoutparser 0.1.3 requires pycocotools==2.0.1, but you have pycocotools 2.0.2 which is incompatible.
> ```
> 
> Could anyone please help me with the working installation version?
> 
> Regards,
> Ankit Aggarwal

If you are on a non-Windows platform, this should be fixed in the v0.2 release of layout parser. Just run `pip install -U layoutparser` should fix your problem. However if you are on a Windows machine, please check https://github.com/Layout-Parser/layout-parser/blob/master/installation.md#for-windows-users .

**Comment by lolipopshock** [comment]
Fixed in #18 and #25 .

**Comment by MarkValadez** [comment]
Hi everyone,

I was install the detectron2 based models, but the program hits a segmentation fault when defining the model `
model = lp.Detectron2LayoutModel('lp://PubLayNet/mask_rcnn_R_50_FPN_3x/config')` there seems to be a dependency issue  with the "black" library. I am unsure if these two are unrelated. I get the following error when installing:

> `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. python-lsp-black 1.2.1 requires black>=22.3.0, but you have black 21.4b2 which is incompatible.`

Thanks in advance for any help.

**Comment by MarkValadez** [comment]
> Hi everyone,
> 
> I was install the detectron2 based models, but the program hits a segmentation fault when defining the model ` model = lp.Detectron2LayoutModel('lp://PubLayNet/mask_rcnn_R_50_FPN_3x/config')` there seems to be a dependency issue with the "black" library. I am unsure if these two are unrelated. I get the following error when installing:
> 
> > `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. python-lsp-black 1.2.1 requires black>=22.3.0, but you have black 21.4b2 which is incompatible.`
> 
> Thanks in advance for any help.

Following up on my previous post, it seems that a poor dependency interplay between conda and pip dependencies caused memory overflows when training the model. I switched to pipenv and that seems to have resolved the issue for now.
