### ISSUE TITLE
[Model suggestion] DiT for document image classification/layout analysis/table detection

### ISSUE THREAD

**Issue by lmmx** [Layout-Parser/layout-parser#134]
The paper on _DiT_ (Document Image Transformer) was revised last week with code and pre-trained models, and I think it’d be a great candidate for inclusion in the LayoutParser library’s model zoo.

- arXiv: [DiT: Self-supervised Pre-training for Document Image Transformer](https://arxiv.org/abs/2203.02378)
- [GitHub repo](https://github.com/microsoft/unilm/tree/master/dit)
- [Interactive demo: Document Layout Analysis with DiT](https://huggingface.co/spaces/nielsr/dit-document-layout-analysis)
- [Interactive demo: Document Image Classification with DiT](https://huggingface.co/spaces/microsoft/document-image-transformer)

**Comment by lolipopshock** [comment]
Thank you @lmmx ! We are planning for the next versions and will take it into account :)
