### ISSUE TITLE
[AutoLayoutModel] Outdated docs and silent error

### ISSUE THREAD

**Issue by falcaopetri** [Layout-Parser/layout-parser#136]
**Describe the bug**
README contains the following (since #73):

> Perform DL layout detection in 4 lines of code
> ```python
> import layoutparser as lp
> model = lp.AutoLayoutModel('lp://EfficientDete/PubLayNet')
> # image = Image.open("path/to/image")
> layout = model.detect(image) 
>   ```

This fails to instantiate a valid model because `AutoLayoutModel` runs
https://github.com/Layout-Parser/layout-parser/blob/89aca0320acbeb8348369dba060bd1c892fbd50f/src/layoutparser/models/auto_layoutmodel.py#L62-L63

and
```python
>>> import layoutparser as lp
>>> list(lp.models.auto_layoutmodel.ALL_AVAILABLE_BACKENDS)
['detectron2', 'paddledetection', 'efficientdet']
```

i.e., 'efficientdet' is not in 'lp://EfficientDete/PubLayNet'.

When `AutoLayoutModel` cannot find a model to instantiate, it silently returns `None` (because it returns nothing).
This means that we get `AttributeError: 'NoneType' object has no attribute 'detect'` during `layout = model.detect(image)`

My suggestions are:
- update the README with a proper model, perhaps from:
https://github.com/Layout-Parser/layout-parser/blob/f230971f7695229ace0c2d68039e466b036101de/tests/test_model.py#L50
- `AutoLayoutModel` should complain if it fails auto detecting the model.
- add `# from PIL import Image` along README's `# image = Image.open("path/to/image")`

**Comment by lolipopshock** [comment]
Thanks -- Good catch! Will fix it later

**Comment by lolipopshock** [comment]
Also see #86
