### ISSUE TITLE
Handling skew image

### ISSUE THREAD

**Issue by phamquiluan** [Layout-Parser/layout-parser#138]
**Enhancement** 🚀
The ability to handle skew document images.

**Motivation**  💪 
Ensuring the document image is in a straight position is beneficial for subsequent steps.

**Additional context** 🧬
There is a package that you can use, https://github.com/phamquiluan/jdeskew

**Comment by Tetsujinfr** [comment]
tbh that is good point but I think you may want to consider using the solution you proposed for yourself, and close this issue. do not think they will add a dependency for this on another package, but may I am wrong.
