### ISSUE TITLE
Extracting information from Invoices

### ISSUE THREAD

**Issue by sriprad** [Layout-Parser/layout-parser#14]
HI Team,

Is it possible to extract the information from invoices of different format and put it in a structured format in an excel?
Please let me know. i am keen to use this library. thanks

**Comment by lolipopshock** [comment]
Thanks for your interest. Though invoice detection is not our focus for now, you might want to check [this dataset](https://rrc.cvc.uab.es/?ch=13&com=tasks) and some related papers (e.g., LayoutLM, https://arxiv.org/pdf/1912.13318.pdf) and see if they are helpful.
