### ISSUE TITLE
unable to install 0.3.4 version of the layoutparser due to assertion error

### ISSUE THREAD

**Issue by felixgao** [Layout-Parser/layout-parser#141]
**Describe the bug**
poetry add layoutparser
Using version ^0.3.4 for layoutparser

Updating dependencies
Resolving dependencies... (0.0s)

  AssertionError

  at ~/.poetry/lib/poetry/mixology/incompatibility.py:111 in __str__
      107│         )
      108│
      109│     def __str__(self):
      110│         if isinstance(self._cause, DependencyCause):
    → 111│             assert len(self._terms) == 2
      112│
      113│             depender = self._terms[0]
      114│             dependee = self._terms[1]
      115│             assert depender.is_positive()

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version, see the [Layout Parser Releases](https://github.com/Layout-Parser/layout-parser/releases/)

**To Reproduce**
1. poetry add layoutparser

**Environment**
1. Please describe your Platform [MacOS]
2. Please show the Layout Parser version
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] poetry 
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

**Screenshots**

**Additional context**

**Comment by lolipopshock** [comment]
Thanks! I think you might want to take a look at poetry's config -- https://github.com/python-poetry/poetry/issues/3491#issuecomment-872230288 .
