### ISSUE TITLE
Any idea about Detectron gets overlapping and sometimes misses some blocks

### ISSUE THREAD

**Issue by rrrokhtar** [Layout-Parser/layout-parser#167]
**The problem**
I am currently using layout-parser to detect the blocks of a scanned book papers and trying to take each block separately from the page and do some processing over them. 

**Checklist**

**To Reproduce**

```python
import layoutparser as lp
import cv2

image = cv2.imread("/content/image_0.jpg")
# Convert the image from BGR (cv2 default loading style) to RGB
image = image[..., ::-1]

model = lp.Detectron2LayoutModel((lp://PrimaLayout/mask_rcnn_R_50_FPN_3x/config),
                                 extra_config=["MODEL.ROI_HEADS.SCORE_THRESH_TEST", 0.8],
                                 label_map={1:"TextRegion", 2:"ImageRegion", 3:"TableRegion", 4:"MathsRegion", 5:"SeparatorRegion", 6:"OtherRegion"})


# Detect the layout of the input image
layout = model.detect(image)

# Show the detected layout of the input image
lp.draw_box(image, layout, box_width=3)
```

**Environment**
1. Platform [Linux] (on colab)
2. Installation commands
```bash
!sudo apt-get update
!sudo apt-get install libleptonica-dev tesseract-ocr libtesseract-dev python3-pil tesseract-ocr-eng tesseract-ocr-script-latn
!pip install layoutparser	
!pip install layoutparser torchvision && pip install "git+https://github.com/facebookresearch/detectron2.git@v0.5#egg=detectron2"	
!pip install "layoutparser[ocr]"	
!pip install "layoutparser[layoutmodels]" # Install DL layout model toolkit 
```
**Screenshots**

1- Overlapping
|![3](https://user-images.githubusercontent.com/39674365/210167423-9679a06d-c2ac-40fa-ad32-fc63ba85ff41.png)|![image_3](https://user-images.githubusercontent.com/39674365/210167469-3f708c67-bfe9-41c1-be93-cf618ff29166.jpg)|
|---|---|

2- Missing
|![7](https://user-images.githubusercontent.com/39674365/210167429-282cdfe3-9c66-4420-9b7f-5e96970b58d3.png)|![image_7](https://user-images.githubusercontent.com/39674365/210167473-402f4d00-8d6d-4ae7-a91a-161da7f8b376.jpg)|
|---|---|

**I know it may not the right place to release that issue, but I think you may have an idea about that problem**

**Comment by prasum** [comment]
@rrrokhtar the pretrained model is trained on scientific and academic research papers. For the above corpus for scanned book paper, https://github.com/Layout-Parser/layout-model-training can be used for custom training
