### ISSUE TITLE
Improper Documentation

### ISSUE THREAD

**Issue by Mukilan-Krishnakumar** [Layout-Parser/layout-parser#195]
**Describe the bug**
Under the Deep Layout Parsing section of the [docs](https://layout-parser.readthedocs.io/en/latest/example/deep_layout_parsing/index.html), the Detectron2LayoutModel is directly imported from Layout Parser but in actuality, it is imported from the models subclass of Layout Parser

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version, see the [Layout Parser Releases](https://github.com/Layout-Parser/layout-parser/releases/)

**To Reproduce**
Visit this [link](https://layout-parser.readthedocs.io/en/latest/example/deep_layout_parsing/index.html) and see it for yourself.

**Environment**
1. Mac OS
2. v0.3.4
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error traceback here.

**Screenshots**
<img width="1440" alt="Screenshot 2023-09-01 at 10 26 49 AM" src="https://github.com/Layout-Parser/layout-parser/assets/71809485/7eb5923a-e929-4cc5-a80f-37a155c51cf5">

**Additional context**

**Comment by Mukilan-Krishnakumar** [comment]
All we need to do is change the `index.rst` file, which can be found [here](https://github.com/Layout-Parser/layout-parser/blob/main/docs/example/deep_layout_parsing/index.rst)

**Comment by drewm23** [comment]
Agreed. Spent a bunch of time trying to debug why my code wasn't working.

**Comment by nkrot** [comment]
This library seems not be maintained any more. Looks like the interest in maintaining it dissipated once the paper was published. 

A quotation for their paper (section 6 Conslusion):

< The LayoutParser team is committed to keeping the library updated continuously and bringing the most recent advances in DL-based DIA, such as multi-modal document modeling (an upcoming priority), to diverse audience of of end-users.

Publish or perish?

**Comment by Mukilan-Krishnakumar** [comment]
Seems like they won't be responding, so I am going to close this.
