### ISSUE TITLE
Adding support for mathematical formula recognition

### ISSUE THREAD

**Issue by SleepyCelery** [Layout-Parser/layout-parser#32]
Have you considered adding support for mathematical formula recognition? Identifying the position of mathematical formulas in documents has always been a problem.

**Comment by lolipopshock** [comment]
Yes, please stay tuned and the model will be released soon.

**Comment by SleepyCelery** [comment]
Thanks a lot.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Shannon Shen ***@***.***>
发送时间: Tuesday, April 20, 2021 2:25:40 AM
收件人: Layout-Parser/layout-parser ***@***.***>
抄送: 巢义虎 ***@***.***>; Author ***@***.***>
主题: Re: [Layout-Parser/layout-parser] Adding support for mathematical formula recognition (#32)


Yes, please stay tuned and the model will be released soon.

―

**Comment by lolipopshock** [comment]
See #59

**Comment by cpwan** [comment]
Is the 79.68 mAP results from the evaluation set or the test set?

**Comment by lolipopshock** [comment]
It's the validation set scores.

**Comment by LunaticMaestro** [comment]
The implementation is failing :(

Find the colab notebook here which I am trying https://colab.research.google.com/drive/1Efiu22l8ax1FgHtsLkLPVagX6UW07u-U?usp=sharing 

(Image used for reference is attached here)
![1](https://github.com/Layout-Parser/layout-parser/assets/38010046/d8583b58-7e29-464f-bc7f-e704ce66e00c)
