### ISSUE TITLE
License agreement of pretrained models

### ISSUE THREAD

**Issue by Tushar-FIS** [Layout-Parser/layout-parser#39]
What are the licensing terms for pretrained models specified in Model Zoo, I am specifically interested in TableBank. As per their website(https://github.com/doc-analysis/TableBank/blob/master/MODEL_ZOO.md) model and data can not be commercially used. However layout-parser is distributed under Apache 2.0, does it mean the TableBank listed here https://layout-parser.readthedocs.io/en/latest/notes/modelzoo.html#model-catalog falls under Apache 2.0 license.

**Comment by lolipopshock** [comment]
Thanks! That's great point! We need to add the appropriate notes for the license for the models. And in the future I believe we can release a version of table detection models with the compatible license.

**Comment by lolipopshock** [comment]
It's great to know that the DocBank/TableBank authors have updated their license to Apache 2.0. And I've checked all other models and they all support for the Apache 2.0 license. I'll keep an eye on the license issue in the future. Thanks!
