### ISSUE TITLE
cant find "'lp://PrimaLayout/mask_rcnn_R_50_FPN_3x/config'" 

### ISSUE THREAD

**Issue by StevenBanama** [Layout-Parser/layout-parser#4]
hi, it 's a awesome project, thx for work. but i cant load pretrain-weight from path which names "'lp://PrimaLayout/mask_rcnn_R_50_FPN_3x/config'". Can u give me a hand to solve it? Tons of thx.

**Comment by lolipopshock** [comment]
Thank you @StevenBanama ! Actually this should be a bug in the previous version. It's already solved by https://github.com/Layout-Parser/layout-parser/commit/8b6156a512cbb0aadc64984bb780c719ab78e107 . You just need to upgrade your layoutparser via `pip install -U layoutparser`.

**Comment by StevenBanama** [comment]
@lolipopshock thx for your effort, it works.
