### ISSUE TITLE
Can we use Yolov5 or other model to do DLA?

### ISSUE THREAD

**Issue by dagongji10** [Layout-Parser/layout-parser#40]
LayoutParser used Faster-RCNN and MaskRCNN to do DLA, but the model size are over 300M, and hard to do inference in android. Maybe DLA is similar with object-detection, so can we use yolov5/tiny-yolo to replace Faster-RCNN/MaskRCNN?

**Comment by lolipopshock** [comment]
#54 this is an even better version of yolo, though it is based on paddledetection - You might need to install extra dependencies to have it running. And I'll have it updated in the next few PRs.
