### ISSUE TITLE
Error in Instantiating lp.GCVAgent

### ISSUE THREAD

**Issue by shumchiken** [Layout-Parser/layout-parser#52]
![image](https://user-images.githubusercontent.com/42760451/127807447-57c9b5ef-cc81-469b-bfdf-9f66900bdf99.png)

**Comment by shumchiken** [comment]
Error when trying to run line 2 in the sample [notebook](https://github.com/Layout-Parser/layout-parser/blob/master/examples/OCR%20Tables%20and%20Parse%20the%20Output.ipynb)

**Comment by shumchiken** [comment]
I've set up my Google Cloud Vision API, installed 'google-cloud-vision' and both are working fine.

**Comment by lolipopshock** [comment]
Please see here https://layout-parser.github.io/tutorials/installation#known-issues . Thanks!
