### ISSUE TITLE
Save the model.pth

### ISSUE THREAD

**Issue by maiia-bocharova** [Layout-Parser/layout-parser#63]
Hello, how can I download the model.pth for further use? I am able to download the config from the model_zoo, but where do I find the final_model.pth file?

Upd: I have found the files in src/layoutparser/models/detectron2/catalog.py
Sorry for asking this

**Comment by lolipopshock** [comment]
In addition to this, if you have already have the models downloaded in layoutparser, you can also go to `~/.torch/iopath_cache/s` to find the downloaded files -- you might need to refer to the `catalog.py` to figure out the model names based on the.
