### ISSUE TITLE
model = lp.Detectron2LayoutModel('lp://PrimaLayout/mask_rcnn_R_50_FPN_3x/config') this step raise the error

### ISSUE THREAD

**Issue by yuansky** [Layout-Parser/layout-parser#8]
![image](https://user-images.githubusercontent.com/9914666/106413970-6bafa300-6486-11eb-966a-2a4f1f126eb6.png)

Can you help me see why this error occurs, thank you very much ！！！

**Comment by lolipopshock** [comment]
Thanks for asking! The major cause is GFW - I don't think Chinese users could have access to dropbox. Currently the proxy solution is to download the configs and weights manually first (you could find it in [model zoos](https://layout-parser.readthedocs.io/en/latest/notes/modelzoo.html)) using a VPN.  In the long term, we will try to cooperate with mirror sits like USTC or Tsinghua Open source mirror to support downloading the weights more conveniently.
