### ISSUE TITLE
Question: Do you have plans to train a more light weight model?

### ISSUE THREAD

**Issue by de-code** [Layout-Parser/layout-parser#82]
**Motivation**

(Apologies if this is not the right place to ask questions)
The `faster_rcnn_R_50_FPN_3x` (PubLayNet) seems to be quite slow on a CPU. Locally it's around 3 seconds per image. In Google Colab it's more than 6 seconds. (It's around 350 ms with a GPU though).
Something that would make this work on a CPU at a more reasonable speed could make it more "accessible".
It would also make the download of the model, and PyTorch itself smaller.
I was wondering whether you have any plans to train a smaller model on one of the related datasets?

**Related resources**
Something like YOLOv5s perhaps?

**Additional context**
n/a

**Comment by lolipopshock** [comment]
Thanks for bringing this up -- yeah, we do have plans to extend to more models. And in the latest updates, we've added models based on EfficientDet, which I've found is typically 90% faster on CPUs. Would you like to have a try -- `lp.AutoLayoutModel("lp://efficientdet/PubLayNet")` ?

**Comment by de-code** [comment]
That is perfect thank you. I should have tried to explore the available models more.
It is indeed much faster and usable (got around 220 ms).
I haven't seen any noticeable reduction in performance for my current use-case (detecting figures, although just looked at one document so far).

**Comment by vikhil0609** [comment]
AutoLayoutModel("lp://efficientdet/PubLayNet")
This can be used for lp.Detectron2LayoutModel also ?
I have trained a custom model I am trying to increase speed for predicting layout detection ?
Need some help it would be glad someone who knows better can help .
