### ISSUE TITLE
Unable to access OCR feature

### ISSUE THREAD

**Issue by ayush2709** [Layout-Parser/layout-parser#93]
Hi Team, 
I have been trying to use layout-parser for my project. 
But I constantly get this issue - 
`AttributeError: module layoutparser has no attribute ocr`

I have installed the OCR module via command `pip install layoutparser[ocr]`

The code that throws this error is - 
`ocr_agent = lp.ocr.TesseractAgent(languages='eng')`

Need help here. Thanks!

**Comment by lolipopshock** [comment]
Could you try the following?
1. `pip install -U layoutparser[ocr]` (adding `-U` for upgrading)
2. `lp.TesseractAgent(languages='eng')` (removing `.ocr`)

**Comment by ayush2709** [comment]
Hey @lolipopshock ,
Thank you for your reply. 

The second option worked for me.
